# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FackDay' do
  use_frameworks!
	pod 'Google-Mobile-Ads-SDK'
	pod 'Alamofire', '~> 5.2'
	pod 'Parchment', '~> 3.0'
	pod 'MiTu'
	pod 'MBProgressHUD', '~> 1.2.0'


end
